CREATE TABLE chemicals.application (
  application_id INT NOT NULL PRIMARY KEY,
  chemical_id INT NOT NULL,
  how_to_use VARCHAR(100),
  chemical_type VARCHAR(100),
  chemical_name VARCHAR(100),
  abbreviation VARCHAR(100),
  crop_name VARCHAR(100),
  applized_place VARCHAR(100),
  pest_and_weed VARCHAR(100),
  type_of_purpose VARCHAR(100),
  dilution_multiple_usage VARCHAR(100),
  dispersion_volume VARCHAR(100),
  period_of_use VARCHAR(100),
  number_of_use VARCHAR(100),
  usage_method VARCHAR(100),
  fumigation_time VARCHAR(100),
  fumigation_temperature VARCHAR(100),
  applicable_soil VARCHAR(100),
  applicable_zone VARCHAR(100),
  applicable_chemical VARCHAR(100),
  num_of_mixed INT,
  restrictions_1 VARCHAR(100),
  restrictions_2 VARCHAR(100),
  restrictions_3 VARCHAR(100),
  restrictions_4 VARCHAR(100),
  restrictions_5 VARCHAR(100)
);